@extends('layouts.app')

@section('title', 'Order #'.$order->id.' - Payment')
@section('content')

<!-- ============================================================ -->
<!-- PAYMENT HEADER -->
<!-- ============================================================ -->
<section class="bg-gradient-to-r from-blue-600 to-blue-800 text-white print:hidden">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div class="flex flex-wrap justify-between items-center gap-4">
            <div>
                <h1 class="text-3xl md:text-4xl font-extrabold flex items-center gap-3">
                    @if($isBakong)
                        <i class="fas fa-qrcode"></i>
                        Pay with Bakong KHQR
                    @else
                        <i class="fas fa-receipt"></i>
                        Payment
                    @endif
                </h1>
                <p class="text-blue-100/90 mt-1">
                    <i class="fas fa-circle text-[6px] mr-2 align-middle"></i>
                    Order #{{ $order->id }} • ${{ number_format($order->total_price, 2) }}
                </p>
            </div>
            <div class="flex gap-2">
                @if($order->payment?->status === 'paid')
                    @if(!$isBakong)
                        <button onclick="window.print()"
                                class="bg-white/20 backdrop-blur-sm hover:bg-white/30 text-white px-6 py-3 rounded-xl font-medium transition flex items-center gap-2 border border-white/20">
                            <i class="fas fa-print"></i>
                            Print
                        </button>
                    @endif
                    <a href="{{ route('customer.orders.show', $order->id) }}"
                       class="bg-white/20 backdrop-blur-sm hover:bg-white/30 text-white px-6 py-3 rounded-xl font-medium transition flex items-center gap-2 border border-white/20">
                        <i class="fas fa-eye"></i>
                        View Order
                    </a>
                @endif
            </div>
        </div>
    </div>
</section>

<!-- ============================================================ -->
<!-- PAYMENT CONTENT -->
<!-- ============================================================ -->
@if($isBakong)
    <!-- Bakong KHQR Payment - Generated by JavaScript -->
    <section class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div class="grid md:grid-cols-2 gap-8">

            <!-- QR Code -->
            <div class="bg-white rounded-2xl shadow-sm border border-slate-100/80 p-6 md:p-8 text-center">
                <h2 class="text-xl font-bold text-slate-800 mb-4 flex items-center justify-center gap-2">
                    <i class="fas fa-qrcode text-blue-500"></i>
                    Scan to Pay
                </h2>

                <div class="bg-slate-50 rounded-2xl p-6 inline-block" id="qrcode-container">
                    <div id="qrcode" class="w-64 h-64 mx-auto flex items-center justify-center">
                        <div class="text-slate-400">
                            <i class="fas fa-spinner fa-spin text-3xl"></i>
                            <p class="text-sm mt-2">Generating QR...</p>
                        </div>
                    </div>
                </div>

                <!-- Amount Display -->
                <div class="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-700">
                    <p class="font-semibold flex items-center justify-center gap-2">
                        <i class="fas fa-dollar-sign"></i>
                        Payment Amount
                    </p>
                    <p class="mt-2 text-2xl font-bold text-blue-800">
                        ${{ number_format($order->total_price, 2) }}
                    </p>
                </div>

                <!-- Reference -->
                <div class="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-700">
                    <p class="font-semibold flex items-center justify-center gap-2">
                        <i class="fas fa-info-circle"></i>
                        Use the reference below in your Bakong app
                    </p>
                    <div class="mt-3 rounded-lg bg-white px-4 py-3 border border-blue-200">
                        <p class="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-600">Reference</p>
                        <p class="mt-1 text-xl font-bold font-mono tracking-wider text-slate-800">
                            INV-{{ str_pad($order->id, 4, '0', STR_PAD_LEFT) }}
                        </p>
                    </div>
                </div>

                <div id="apiError" class="mt-4 text-sm text-amber-600 bg-amber-50 p-3 rounded-xl hidden">
                    <i class="fas fa-exclamation-triangle mr-1"></i>
                    <span id="apiErrorMessage"></span>
                </div>
            </div>

            <!-- Instructions & Verification -->
            <div class="bg-white rounded-2xl shadow-sm border border-slate-100/80 p-6 md:p-8">
                <h2 class="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                    <i class="fas fa-info-circle text-blue-500"></i>
                    Payment Instructions
                </h2>

                <ul class="space-y-4 text-sm text-slate-600">
                    <li class="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                        <span class="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-blue-500 font-bold text-xs flex-shrink-0">1</span>
                        <span>Open your <strong class="text-slate-700">Bakong</strong> mobile app</span>
                    </li>
                    <li class="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                        <span class="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-blue-500 font-bold text-xs flex-shrink-0">2</span>
                        <span>Scan the <strong class="text-slate-700">QR code</strong> on the left</span>
                    </li>
                    <li class="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                        <span class="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-blue-500 font-bold text-xs flex-shrink-0">3</span>
                        <span>Confirm the payment amount: <strong class="text-slate-700">${{ number_format($order->total_price, 2) }}</strong></span>
                    </li>
                    <li class="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                        <span class="w-6 h-6 bg-blue-100 rounded-full flex items-center justify-center text-blue-500 font-bold text-xs flex-shrink-0">4</span>
                        <span>Wait for confirmation and return here</span>
                    </li>
                </ul>

                <!-- Verify Button -->
                <button id="verifyPaymentBtn"
                        class="w-full mt-6 bg-gradient-to-r from-blue-600 to-blue-800 hover:from-blue-700 hover:to-blue-900 text-white py-3.5 rounded-xl font-semibold transition flex items-center justify-center gap-2 shadow-lg shadow-blue-500/25">
                    <i class="fas fa-rotate-right"></i>
                    Check Payment Status
                </button>

                <div id="paymentStatus" class="mt-4 text-sm text-slate-500 text-center"></div>

                <div id="autoPaymentHint" class="mt-3 text-xs text-slate-400 text-center flex items-center justify-center gap-2">
                    <i class="fas fa-circle text-[6px] text-blue-400"></i>
                    Auto-checking payment every 10 seconds
                </div>
            </div>

        </div>
    </section>
@elseif($order->payment?->status === 'paid')
    <!-- Cash Receipt (paid) -->
    <section class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div class="bg-white rounded-2xl shadow-sm border border-slate-100/80 overflow-hidden" id="receipt-content">

            <!-- Receipt Header -->
            <div class="p-8 border-b border-slate-200 text-center">
                <div class="flex items-center justify-center gap-3 mb-4">
                    <div class="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center">
                        <i class="fas fa-utensils text-white text-xl"></i>
                    </div>
                    <span class="text-2xl font-bold text-slate-800">
                        Food<span class="text-blue-600">Restaurant</span>
                    </span>
                </div>
                <h2 class="text-lg font-semibold text-slate-600">Payment Receipt</h2>
                <p class="text-sm text-slate-400 mt-1">
                    <i class="fas fa-calendar-alt mr-1"></i>
                    {{ $order->created_at->format('l, F d, Y - h:i A') }}
                </p>
            </div>

            <!-- Invoice Info -->
            <div class="p-6 border-b border-slate-200 bg-slate-50/50">
                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <p class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Invoice Number</p>
                        <p class="text-lg font-bold text-slate-800 mt-1">
                            {{ $order->payment?->reference_no ?? 'INV-'.str_pad($order->id, 4, '0', STR_PAD_LEFT) }}
                        </p>
                    </div>
                    <div>
                        <p class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Customer Name</p>
                        <p class="text-lg font-bold text-slate-800 mt-1">{{ $order->customer?->name ?? 'N/A' }}</p>
                    </div>
                    <div>
                        <p class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Payment Method</p>
                        <p class="text-base font-medium text-slate-700 mt-1">
                            <i class="fas fa-money-bill-wave text-emerald-500 mr-1"></i>Cash on Delivery
                        </p>
                    </div>
                    <div>
                        <p class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Payment Status</p>
                        <p class="text-base font-medium mt-1 text-emerald-600">
                            <i class="fas fa-check-circle mr-1"></i>Paid
                        </p>
                    </div>
                </div>
            </div>

            <!-- Order Items -->
            <div class="p-6">
                <h3 class="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">Order Items</h3>

                <table class="w-full">
                    <thead>
                        <tr class="border-b border-slate-200">
                            <th class="pb-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">#</th>
                            <th class="pb-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Item</th>
                            <th class="pb-3 text-center text-xs font-semibold text-slate-400 uppercase tracking-wider">Qty</th>
                            <th class="pb-3 text-right text-xs font-semibold text-slate-400 uppercase tracking-wider">Price</th>
                            <th class="pb-3 text-right text-xs font-semibold text-slate-400 uppercase tracking-wider">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($order->orderItems as $item)
                        <tr class="border-b border-slate-100">
                            <td class="py-3 text-sm text-slate-400">{{ $loop->iteration }}</td>
                            <td class="py-3 font-medium text-slate-700">
                                {{ $item->product?->name ?? 'Product #'.$item->product_id }}
                            </td>
                            <td class="py-3 text-center text-slate-600">{{ $item->quantity }}</td>
                            <td class="py-3 text-right text-slate-600">${{ number_format($item->price, 2) }}</td>
                            <td class="py-3 text-right font-bold text-blue-600">${{ number_format($item->quantity * $item->price, 2) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <!-- Totals -->
            <div class="p-6 border-t border-slate-200 bg-slate-50/50">
                <div class="flex justify-end">
                    <div class="w-64 space-y-2">
                        <div class="flex justify-between text-sm">
                            <span class="text-slate-500">Subtotal</span>
                            <span class="font-medium text-slate-700">${{ number_format($order->total_price, 2) }}</span>
                        </div>
                        <div class="flex justify-between text-sm">
                            <span class="text-slate-500">Delivery Fee</span>
                            <span class="font-medium text-slate-700">$2.50</span>
                        </div>
                        <div class="flex justify-between text-sm">
                            <span class="text-slate-500">Tax (10%)</span>
                            <span class="font-medium text-slate-700">${{ number_format($order->total_price * 0.10, 2) }}</span>
                        </div>
                        <div class="border-t border-slate-200 pt-2 flex justify-between">
                            <span class="text-lg font-bold text-slate-800">Total Amount</span>
                            <span class="text-lg font-bold text-blue-600">${{ number_format($order->total_price + 2.50 + ($order->total_price * 0.10), 2) }}</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Footer -->
            <div class="p-6 text-center border-t border-slate-200">
                <div class="flex items-center justify-center gap-2 text-sm text-slate-400 mb-2">
                    <i class="fas fa-check-circle text-emerald-500"></i>
                    <span>Order #{{ $order->id }} - {{ $order->status === 'completed' ? 'Completed' : ucfirst($order->status) }}</span>
                </div>
                <p class="text-xs text-slate-400">
                    <i class="fas fa-utensils mr-1"></i>
                    Thank you for dining with FoodRestaurant!
                </p>
                <div class="mt-3 flex items-center justify-center gap-4 text-xs text-slate-400">
                    <span><i class="fas fa-phone mr-1"></i>+855 12 345 678</span>
                    <span><i class="fas fa-envelope mr-1"></i>info@foodrestaurant.com</span>
                </div>
            </div>

        </div>

        <!-- Action Buttons -->
        <div class="flex justify-center gap-4 mt-6 print:hidden">
            <a href="{{ route('customer.orders.show', $order->id) }}"
               class="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3.5 rounded-xl font-semibold transition inline-flex items-center gap-2 shadow-lg shadow-blue-500/25">
                <i class="fas fa-eye"></i>
                View Order Status
            </a>
            <button onclick="downloadReceipt()"
                    class="bg-white hover:bg-slate-50 text-blue-600 border border-blue-200 px-8 py-3.5 rounded-xl font-semibold transition inline-flex items-center gap-2">
                <i class="fas fa-download"></i>
                Download Receipt
            </button>
        </div>
    </section>
@else
    <!-- Cash Payment - Pending -->
    <section class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div class="bg-white rounded-2xl shadow-sm border border-slate-100/80 p-8 text-center">
            <div class="w-20 h-20 bg-amber-100 rounded-full flex items-center justify-center mx-auto mb-6">
                <i class="fas fa-money-bill-wave text-amber-500 text-3xl"></i>
            </div>

            <h2 class="text-2xl font-bold text-slate-800 mb-2">Cash on Delivery</h2>
            <p class="text-slate-500 mb-2">Order #{{ $order->id }}</p>
            <p class="text-3xl font-bold text-blue-600 mb-6">${{ number_format($order->total_price, 2) }}</p>

            <div class="max-w-md mx-auto bg-slate-50 rounded-xl p-6 mb-6 text-left">
                <h3 class="font-semibold text-slate-700 mb-3 flex items-center gap-2">
                    <i class="fas fa-info-circle text-blue-500"></i>
                    Order Summary
                </h3>
                <div class="space-y-2 text-sm">
                    <div class="flex justify-between">
                        <span class="text-slate-500">Items</span>
                        <span class="font-medium text-slate-700">{{ $order->orderItems->count() }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-slate-500">Payment Method</span>
                        <span class="font-medium text-slate-700">
                            <i class="fas fa-money-bill-wave text-emerald-500 mr-1"></i>Cash on Delivery
                        </span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-slate-500">Payment Status</span>
                        <span class="font-medium text-amber-600">
                            <i class="fas fa-clock mr-1"></i>Pending
                        </span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-slate-500">Delivery Address</span>
                        <span class="font-medium text-slate-700 text-right max-w-[200px]">{{ $order->customer?->address ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>

            <div class="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6 text-sm text-blue-700 text-left">
                <p class="flex items-start gap-2">
                    <i class="fas fa-info-circle mt-0.5"></i>
                    <span>Please prepare <strong>${{ number_format($order->total_price, 2) }}</strong> in cash for the delivery. Click "I Have Paid" once you've handed the cash to the delivery person.</span>
                </p>
            </div>

            <!-- Confirm Payment Button -->
            <button id="confirmCashBtn"
                    class="w-full max-w-md bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-600 hover:to-emerald-700 text-white py-3.5 rounded-xl font-semibold transition flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/25 mx-auto">
                <i class="fas fa-check-circle"></i>
                I Have Paid - Confirm Payment
            </button>

            <div id="confirmStatus" class="mt-4 text-sm text-slate-500 text-center"></div>
        </div>
    </section>
@endif

<!-- ============================================================ -->
<!-- SCRIPTS -->
<!-- ============================================================ -->

<!-- QRCode.js CDN for JS-based QR generation -->
<script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script>

@if($isBakong)
<script>
    window.customerPaymentQr = {
        data: @json($qr['qr_data'] ?? ''),
        image: @json($qr['qr_image'] ?? ''),
    };

    // ===== Generate KHQR using JavaScript fallback =====
    const BAKONG_MERCHANT_ID = '{{ $merchantAccountId }}';
    const MERCHANT_NAME = '{{ $merchantName }}';
    const MERCHANT_CITY = '{{ $merchantCity }}';
    const ORDER_TOTAL = {{ $order->total_price }};
    const ORDER_ID = {{ $order->id }};

    function generateKHQR() {
        // Bakong KHQR format (simplified merchant individual QR)
        // Format: merchant_account_id|merchant_name|merchant_city|amount|currency|store_label|terminal_label
        const khqrData = [
            BAKONG_MERCHANT_ID,
            MERCHANT_NAME,
            MERCHANT_CITY,
            ORDER_TOTAL.toFixed(2),
            'USD',
            'FoodRestaurant',
            'POS'
        ].join('|');

        return khqrData;
    }

    function renderQRCode() {
        const qrContainer = document.getElementById('qrcode');
        qrContainer.innerHTML = '';

        if (window.customerPaymentQr.image) {
            qrContainer.innerHTML = `<img src="${window.customerPaymentQr.image}" alt="Bakong KHQR" class="w-64 h-64 object-contain">`;
            return;
        }

        const khqrString = window.customerPaymentQr.data || generateKHQR();

        try {
            // Generate QR code using qrcodejs library
            const qr = new QRCode(qrContainer, {
                text: khqrString,
                width: 260,
                height: 260,
                colorDark: '#1e293b',
                colorLight: '#ffffff',
                correctLevel: QRCode.CorrectLevel.H
            });

            console.log('✅ KHQR generated successfully via JavaScript');
            console.log('📱 QR Data:', khqrString);
        } catch (e) {
            console.error('❌ QR Generation failed:', e);
            qrContainer.innerHTML = `
                <div class="text-slate-400 text-center p-4">
                    <i class="fas fa-exclamation-triangle text-3xl block mb-2"></i>
                    <p class="text-sm">Could not generate QR code</p>
                    <p class="text-xs mt-1 font-mono break-all">${khqrString}</p>
                </div>
            `;
        }
    }

    // Render QR on page load
    document.addEventListener('DOMContentLoaded', function() {
        renderQRCode();
    });

    // ===== Payment Verification =====
    const verifyBtn = document.getElementById('verifyPaymentBtn');
    const statusBox = document.getElementById('paymentStatus');
    const autoHint = document.getElementById('autoPaymentHint');
    let isChecking = false;
    let checkCount = 0;
    let isPaid = false;

    function verifyPayment() {
        if (isChecking || isPaid) return;

        isChecking = true;
        checkCount++;
        verifyBtn.disabled = true;
        verifyBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Checking...';
        statusBox.className = 'mt-4 text-sm text-slate-500 text-center';
        statusBox.textContent = 'Checking payment status... (Attempt ' + checkCount + ')';

        fetch('{{ route('customer.payment.verify', $order->id) }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}',
                'Accept': 'application/json',
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data.success && data.is_paid) {
                isPaid = true;
                statusBox.className = 'mt-4 text-sm text-emerald-600 text-center font-medium';
                statusBox.innerHTML = '<i class="fas fa-check-circle mr-2"></i> ' + (data.message || 'Payment verified!');
                autoHint.textContent = '✅ Payment confirmed!';

                // Auto-redirect to order page after 2 seconds
                setTimeout(() => {
                    window.location.href = '{{ route("customer.orders.show", $order->id) }}';
                }, 2000);

                return;
            }

            statusBox.className = 'mt-4 text-sm text-amber-600 text-center';
            statusBox.innerHTML = '<i class="fas fa-clock mr-2"></i> ' + (data.message || 'Payment is still pending');
            autoHint.textContent = '🔄 Auto-checking payment every 10 seconds (Attempt ' + checkCount + ')';
        })
        .catch(error => {
            statusBox.className = 'mt-4 text-sm text-rose-600 text-center';
            statusBox.innerHTML = '<i class="fas fa-exclamation-circle mr-2"></i> Unable to verify payment right now';
            autoHint.textContent = '⚠️ Retrying in 10 seconds';
            console.error(error);
        })
        .finally(() => {
            isChecking = false;
            verifyBtn.disabled = false;
            verifyBtn.innerHTML = '<i class="fas fa-rotate-right mr-2"></i> Check Payment Status';
        });
    }

    // Event listener
    verifyBtn.addEventListener('click', verifyPayment);

    // Auto-check every 10 seconds
    setTimeout(() => {
        verifyPayment();
    }, 2000);
    const interval = setInterval(verifyPayment, 10000);

    // Cleanup on page unload
    window.addEventListener('beforeunload', function() {
        clearInterval(interval);
    });

    // Check if already paid on page load (redirect with SweetAlert2)
    @if($order->payment?->status === 'paid' || $order->status !== 'pending_payment')
        isPaid = true;
        // Auto-redirect to order page after 2 seconds
        setTimeout(() => {
            window.location.href = '{{ route("customer.orders.show", $order->id) }}';
        }, 2000);
    @endif

    console.log('🏦 Bakong Payment page loaded (JS QR)');
    console.log('📦 Order ID:', ORDER_ID);
</script>
@elseif($order->payment?->status === 'paid')
<script>
    function downloadReceipt() {
        const content = document.getElementById('receipt-content');
        const clone = content.cloneNode(true);
        
        // Create a new window for printing
        const win = window.open('', '_blank');
        win.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>Receipt #{{ $order->id }}</title>
                <script src="https://cdn.tailwindcss.com">
                <\/script>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
                <style>
                    body { 
                        font-family: 'Inter', sans-serif;
                        padding: 2rem;
                        max-width: 800px;
                        margin: 0 auto;
                    }
                    @media print {
                        body { padding: 0; }
                    }
                </style>
            </head>
            <body>
                ${clone.outerHTML}
                <script>
                    window.onload = function() {
                        window.print();
                        setTimeout(function() { window.close(); }, 1000);
                    }
                <\/script>
            </body>
            </html>
        `);
        win.document.close();
    }

    console.log('🧾 Payment Receipt page loaded');
</script>
@else
<script>
    const confirmBtn = document.getElementById('confirmCashBtn');
    const confirmStatus = document.getElementById('confirmStatus');
    let isConfirming = false;

    confirmBtn.addEventListener('click', function() {
        if (isConfirming) return;

        // Show confirmation dialog
        Swal.fire({
            title: 'Confirm Payment?',
            text: 'Have you paid ${{ number_format($order->total_price, 2) }} in cash?',
            icon: 'question',
            showCancelButton: true,
            confirmButtonColor: '#10b981',
            cancelButtonColor: '#64748b',
            confirmButtonText: '<i class="fas fa-check-circle mr-2"></i>Yes, I Have Paid',
            cancelButtonText: 'Cancel',
            reverseButtons: true,
        }).then((result) => {
            if (result.isConfirmed) {
                confirmPayment();
            }
        });
    });

    function confirmPayment() {
        isConfirming = true;
        confirmBtn.disabled = true;
        confirmBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Confirming...';
        confirmStatus.className = 'mt-4 text-sm text-slate-500 text-center';
        confirmStatus.textContent = 'Confirming your payment...';

        fetch('{{ route('customer.payment.confirm-cash', $order->id) }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}',
                'Accept': 'application/json',
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data.success && data.is_paid) {
                confirmStatus.className = 'mt-4 text-sm text-emerald-600 text-center font-medium';
                confirmStatus.innerHTML = '<i class="fas fa-check-circle mr-2"></i> ' + (data.message || 'Payment confirmed!');

                Swal.fire({
                    icon: 'success',
                    title: 'Payment Confirmed!',
                    text: data.message || 'Your order is now pending restaurant acceptance.',
                    confirmButtonColor: '#2563eb',
                    confirmButtonText: 'View Order',
                }).then(() => {
                    window.location.href = '{{ route("customer.orders.show", $order->id) }}';
                });
            } else {
                confirmStatus.className = 'mt-4 text-sm text-rose-600 text-center';
                confirmStatus.innerHTML = '<i class="fas fa-exclamation-circle mr-2"></i> ' + (data.message || 'Something went wrong');
                isConfirming = false;
                confirmBtn.disabled = false;
                confirmBtn.innerHTML = '<i class="fas fa-check-circle"></i> I Have Paid - Confirm Payment';
            }
        })
        .catch(error => {
            confirmStatus.className = 'mt-4 text-sm text-rose-600 text-center';
            confirmStatus.innerHTML = '<i class="fas fa-exclamation-circle mr-2"></i> Unable to confirm payment right now';
            isConfirming = false;
            confirmBtn.disabled = false;
            confirmBtn.innerHTML = '<i class="fas fa-check-circle"></i> I Have Paid - Confirm Payment';
            console.error(error);
        });
    }

    console.log('💰 Cash Payment page loaded');
</script>
@endif

<!-- ============================================================ -->
<!-- STYLES -->
<!-- ============================================================ -->
<style>
    /* QR Code hover effect */
    .qr-container img {
        transition: transform 0.3s ease;
    }
    .qr-container img:hover {
        transform: scale(1.02);
    }

    /* Pulse animation for pending status */
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.5; }
    }
    .pulse-status {
        animation: pulse 2s ease-in-out infinite;
    }

    @media print {
        body {
            background: white !important;
        }
        .print\:hidden {
            display: none !important;
        }
        #receipt-content {
            box-shadow: none !important;
            border: none !important;
            border-radius: 0 !important;
        }
    }

    /* Receipt hover */
    #receipt-content {
        transition: box-shadow 0.3s ease;
    }
    #receipt-content:hover {
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
    }

    /* Responsive */
    @media (max-width: 768px) {
        .md\:grid-cols-2 {
            grid-template-columns: 1fr;
        }
        .w-64 {
            width: 200px;
            height: 200px;
        }
    }

    /* Scrollbar */
    ::-webkit-scrollbar {
        width: 4px;
    }
    ::-webkit-scrollbar-track {
        background: #f1f5f9;
        border-radius: 8px;
    }
    ::-webkit-scrollbar-thumb {
        background: #cbd5e1;
        border-radius: 8px;
    }
</style>

@endsection
